name: CI

on: push

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      FIREBASE_URL: foo
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            server/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Update local toolchain
        run: |
          rustup update
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint
        run: |
          cd server
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Build
        run: |
          cd server
          cargo build --release